// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-7zAzEyojth8ch2b-buS_9cy09O_v4o',
    appId: '1:774529955505:web:7f93cac796c265d2299490',
    messagingSenderId: '774529955505',
    projectId: 'nss-event-management-app-c040f',
    authDomain: 'nss-event-management-app-c040f.firebaseapp.com',
    storageBucket: 'nss-event-management-app-c040f.appspot.com',
    measurementId: 'G-2PQF9F4243',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-TI-j5jU3y7bQGPWvhNt4Jjk3K_QjtY8',
    appId: '1:774529955505:android:241d5244bee3e8ec299490',
    messagingSenderId: '774529955505',
    projectId: 'nss-event-management-app-c040f',
    storageBucket: 'nss-event-management-app-c040f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9CRI8QB2q1FZg3IpqCH8LcueZnSwYGa4',
    appId: '1:774529955505:ios:15388857df699f0e299490',
    messagingSenderId: '774529955505',
    projectId: 'nss-event-management-app-c040f',
    storageBucket: 'nss-event-management-app-c040f.appspot.com',
    iosBundleId: 'com.example.nssProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9CRI8QB2q1FZg3IpqCH8LcueZnSwYGa4',
    appId: '1:774529955505:ios:15388857df699f0e299490',
    messagingSenderId: '774529955505',
    projectId: 'nss-event-management-app-c040f',
    storageBucket: 'nss-event-management-app-c040f.appspot.com',
    iosBundleId: 'com.example.nssProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-7zAzEyojth8ch2b-buS_9cy09O_v4o',
    appId: '1:774529955505:web:a4deb4f1d30a1f83299490',
    messagingSenderId: '774529955505',
    projectId: 'nss-event-management-app-c040f',
    authDomain: 'nss-event-management-app-c040f.firebaseapp.com',
    storageBucket: 'nss-event-management-app-c040f.appspot.com',
    measurementId: 'G-K8JCHR1T1K',
  );
}
